version: '3.2'

services:
  elasticsearch01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
        type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/logs
        target: /usr/share/elasticsearch/logs
        read_only: false
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch01
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      - ELASTIC_PASSWORD: changeme
    networks:
      - elk

  elasticsearch02:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
        type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/logs
        target: /usr/share/elasticsearch/logs
        read_only: false
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch02
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch01,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      - ELASTIC_PASSWORD: changeme
    networks:
      - elk

  elasticsearch03:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
        type: bind
        source: ./elasticsearch/config/log4j2.properties
        target: /usr/share/elasticsearch/config/log4j2.properties
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elasticsearch/logs
        target: /usr/share/elasticsearch/logs
        read_only: false
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch03
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch01,elasticsearch02
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      - ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
